public enum ExecutionCode {
    SUCCESS,
    NULL,
    NOT_EMPTY,
    NOT_OWNER,
    NOT_ADJACENT,
    INVALID_POSITION,
    INVALID_MILL_POSITION,
    NOT_OPPONENT_PIECE,
    OPPONENT_PIECE_IN_MILL_POSITION,
    MILL_FORMED,
    Quit,
    Undo,
    Removed,
    UNKNOWN
}