public enum GameHandlerStatus {
    INACTIVE(),
    INACTIVE_LOAD_FAILED(),
    RUNNING(),
    GAME_SAVE_SUCCESS(),
    GAME_LOAD_SUCCESS(),
    GAME_SAVE_FAILED(),
    GAME_LOAD_FAILED(),
    GAME_LOAD_CANCELLED(),
    GAME_LOAD_FAILED_EMPTY_FILE(),
    UNDO_SUCCESS(),
    UNDO_FAILED();
}
